# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stone_bot.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Stone(object):
    def setupUi(self, Stone):
        Stone.setObjectName("Stone")
        Stone.resize(710, 520)
        Stone.setMinimumSize(QtCore.QSize(710, 520))
        self.startbutton = QtWidgets.QPushButton(Stone)
        self.startbutton.setGeometry(QtCore.QRect(510, 490, 75, 23))
        self.startbutton.setObjectName("startbutton")
        self.pausebutton = QtWidgets.QPushButton(Stone)
        self.pausebutton.setGeometry(QtCore.QRect(610, 490, 75, 23))
        self.pausebutton.setObjectName("pausebutton")
        self.tab_widget = QtWidgets.QTabWidget(Stone)
        self.tab_widget.setGeometry(QtCore.QRect(10, 0, 691, 491))
        self.tab_widget.setMinimumSize(QtCore.QSize(691, 491))
        self.tab_widget.setMaximumSize(QtCore.QSize(691, 491))
        self.tab_widget.setToolTip("")
        self.tab_widget.setObjectName("tab_widget")
        self.log = QtWidgets.QWidget()
        self.log.setObjectName("log")
        self.chattext = QtWidgets.QTextEdit(self.log)
        self.chattext.setGeometry(QtCore.QRect(360, 0, 331, 471))
        self.chattext.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.chattext.setObjectName("chattext")
        self.logtext = QtWidgets.QPlainTextEdit(self.log)
        self.logtext.setGeometry(QtCore.QRect(0, 0, 361, 471))
        self.logtext.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.logtext.setReadOnly(True)
        self.logtext.setMaximumBlockCount(1024)
        self.logtext.setCenterOnScroll(True)
        self.logtext.setObjectName("logtext")
        self.tab_widget.addTab(self.log, "")
        self.setting = QtWidgets.QWidget()
        self.setting.setObjectName("setting")
        self.ad_remove_checker = QtWidgets.QCheckBox(self.setting)
        self.ad_remove_checker.setGeometry(QtCore.QRect(10, 60, 121, 41))
        self.ad_remove_checker.setObjectName("ad_remove_checker")
        self.restart_timer = QtWidgets.QSpinBox(self.setting)
        self.restart_timer.setGeometry(QtCore.QRect(90, 10, 42, 22))
        self.restart_timer.setMinimum(1)
        self.restart_timer.setMaximum(24)
        self.restart_timer.setObjectName("restart_timer")
        self.restart_label = QtWidgets.QLabel(self.setting)
        self.restart_label.setGeometry(QtCore.QRect(10, 10, 81, 20))
        self.restart_label.setObjectName("restart_label")
        self.dir_string = QtWidgets.QLineEdit(self.setting)
        self.dir_string.setGeometry(QtCore.QRect(10, 140, 211, 20))
        self.dir_string.setObjectName("dir_string")
        self.path_label = QtWidgets.QLabel(self.setting)
        self.path_label.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.path_label.setObjectName("path_label")
        self.dir = QtWidgets.QToolButton(self.setting)
        self.dir.setGeometry(QtCore.QRect(220, 140, 22, 18))
        self.dir.setObjectName("dir")
        self.save_setting = QtWidgets.QPushButton(self.setting)
        self.save_setting.setGeometry(QtCore.QRect(570, 410, 75, 23))
        self.save_setting.setObjectName("save_setting")
        self.DEBUG = QtWidgets.QCheckBox(self.setting)
        self.DEBUG.setGeometry(QtCore.QRect(10, 430, 81, 16))
        self.DEBUG.setObjectName("DEBUG")
        self.emu_name = QtWidgets.QLineEdit(self.setting)
        self.emu_name.setGeometry(QtCore.QRect(10, 200, 113, 20))
        self.emu_name.setObjectName("emu_name")
        self.name_label = QtWidgets.QLabel(self.setting)
        self.name_label.setGeometry(QtCore.QRect(10, 180, 71, 16))
        self.name_label.setObjectName("name_label")
        self.always_fast_mining_checker = QtWidgets.QCheckBox(self.setting)
        self.always_fast_mining_checker.setGeometry(QtCore.QRect(130, 60, 121, 41))
        self.always_fast_mining_checker.setObjectName("always_fast_mining_checker")
        self.min_sleep_box = QtWidgets.QSpinBox(self.setting)
        self.min_sleep_box.setGeometry(QtCore.QRect(230, 70, 42, 22))
        self.min_sleep_box.setObjectName("min_sleep_box")
        self.max_sleep_box = QtWidgets.QSpinBox(self.setting)
        self.max_sleep_box.setGeometry(QtCore.QRect(310, 70, 42, 22))
        self.max_sleep_box.setObjectName("max_sleep_box")
        self.min_label = QtWidgets.QLabel(self.setting)
        self.min_label.setGeometry(QtCore.QRect(280, 70, 47, 21))
        self.min_label.setObjectName("min_label")
        self.max_label = QtWidgets.QLabel(self.setting)
        self.max_label.setGeometry(QtCore.QRect(360, 70, 47, 21))
        self.max_label.setObjectName("max_label")
        self.random_sleep_label = QtWidgets.QLabel(self.setting)
        self.random_sleep_label.setGeometry(QtCore.QRect(280, 50, 47, 12))
        self.random_sleep_label.setObjectName("random_sleep_label")
        self.adb_test_checkBox = QtWidgets.QCheckBox(self.setting)
        self.adb_test_checkBox.setGeometry(QtCore.QRect(110, 430, 91, 16))
        self.adb_test_checkBox.setObjectName("adb_test_checkBox")
        self.mining_level = QtWidgets.QSpinBox(self.setting)
        self.mining_level.setGeometry(QtCore.QRect(220, 10, 42, 22))
        self.mining_level.setMaximum(2)
        self.mining_level.setObjectName("mining_level")
        self.mining_level_label = QtWidgets.QLabel(self.setting)
        self.mining_level_label.setGeometry(QtCore.QRect(150, 10, 61, 21))
        self.mining_level_label.setObjectName("mining_level_label")
        self.mining_level_doc = QtWidgets.QLabel(self.setting)
        self.mining_level_doc.setGeometry(QtCore.QRect(270, 10, 191, 21))
        self.mining_level_doc.setObjectName("mining_level_doc")
        self.tab_widget.addTab(self.setting, "")
        self.restart_label.setBuddy(self.restart_timer)

        self.retranslateUi(Stone)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Stone)
        Stone.setTabOrder(self.tab_widget, self.startbutton)
        Stone.setTabOrder(self.startbutton, self.pausebutton)
        Stone.setTabOrder(self.pausebutton, self.chattext)
        Stone.setTabOrder(self.chattext, self.logtext)
        Stone.setTabOrder(self.logtext, self.ad_remove_checker)
        Stone.setTabOrder(self.ad_remove_checker, self.restart_timer)
        Stone.setTabOrder(self.restart_timer, self.dir_string)
        Stone.setTabOrder(self.dir_string, self.dir)

    def retranslateUi(self, Stone):
        _translate = QtCore.QCoreApplication.translate
        Stone.setWindowTitle(_translate("Stone", "Stone bot"))
        self.startbutton.setText(_translate("Stone", "開始"))
        self.pausebutton.setText(_translate("Stone", "暫停"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.log), _translate("Stone", "主功能"))
        self.ad_remove_checker.setText(_translate("Stone", "去廣告"))
        self.restart_label.setText(_translate("Stone", "重啟時間"))
        self.path_label.setText(_translate("Stone", "模擬器路徑"))
        self.dir.setText(_translate("Stone", "..."))
        self.save_setting.setText(_translate("Stone", "保存設置"))
        self.DEBUG.setText(_translate("Stone", "debug mode"))
        self.name_label.setText(_translate("Stone", "模擬器名稱"))
        self.always_fast_mining_checker.setText(_translate("Stone", "永遠快礦"))
        self.min_label.setText(_translate("Stone", "下限"))
        self.max_label.setText(_translate("Stone", "上限"))
        self.random_sleep_label.setText(_translate("Stone", "隨機休息時間"))
        self.adb_test_checkBox.setText(_translate("Stone", "adb test mode"))
        self.mining_level_label.setText(_translate("Stone", "快礦等級"))
        self.mining_level_doc.setText(_translate("Stone", "0 代表不開 1等於藍 2等於紅"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.setting), _translate("Stone", "設定"))

